name: docs-build
on :
  push:
    branches:
      - main
    paths:
      - "mcat/*.py"

jobs:
  docs-build:
    name: Automatic docs build
    runs-on: ubuntu-latest
    env:
      # see tox.ini
      TOXENV: docs

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade tox

      - name: Run tox (${{ env.TOXENV }})
        run: tox

      - name: Commit docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@users.noreply.github.com'
          git add -A
          git commit -s -m "Build docs"
          git push
